-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE trial_accounts ADD COLUMN IF NOT EXISTS disabled BOOLEAN DEFAULT false;
