-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS trial_accounts (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 email TEXT NOT NULL UNIQUE,
 password TEXT NOT NULL,
 expiry TIMESTAMPTZ NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE trial_accounts ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
 IF NOT EXISTS (
  SELECT 1 FROM pg_policies
  WHERE schemaname = 'public'
   AND tablename = 'trial_accounts'
   AND policyname = 'anon_select_trial_accounts'
 ) THEN
  CREATE POLICY anon_select_trial_accounts ON trial_accounts
   FOR SELECT
   USING (true);
 END IF;

 IF NOT EXISTS (
  SELECT 1 FROM pg_policies
  WHERE schemaname = 'public'
   AND tablename = 'trial_accounts'
   AND policyname = 'anon_insert_trial_accounts'
 ) THEN
  CREATE POLICY anon_insert_trial_accounts ON trial_accounts
   FOR INSERT
   WITH CHECK (true);
 END IF;

 IF NOT EXISTS (
  SELECT 1 FROM pg_policies
  WHERE schemaname = 'public'
   AND tablename = 'trial_accounts'
   AND policyname = 'anon_update_trial_accounts'
 ) THEN
  CREATE POLICY anon_update_trial_accounts ON trial_accounts
   FOR UPDATE
   USING (true);
 END IF;

 IF NOT EXISTS (
  SELECT 1 FROM pg_policies
  WHERE schemaname = 'public'
   AND tablename = 'trial_accounts'
   AND policyname = 'anon_delete_trial_accounts'
 ) THEN
  CREATE POLICY anon_delete_trial_accounts ON trial_accounts
   FOR DELETE
   USING (true);
 END IF;
END $$;
