/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as DemoLoginRouteImport } from './routes/demo-login'
import { Route as CertificatesTestRouteImport } from './routes/certificates-test'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as PlatformAdminRouteImport } from './routes/platform.admin'
import { Route as AppScriptsRouteImport } from './routes/app/scripts'
import { Route as AppPricingRouteImport } from './routes/app/pricing'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppHelpRouteImport } from './routes/app/help'
import { Route as AppEditorRouteImport } from './routes/app/editor'
import { Route as AppChangelogRouteImport } from './routes/app/changelog'
import { Route as AppCertificatesDetailRouteImport } from './routes/app/certificates-detail'
import { Route as AppCertificatesRouteImport } from './routes/app/certificates'
import { Route as AppCertificateSingleRouteImport } from './routes/app/certificate-single'
import { Route as AppCertificateRouteImport } from './routes/app/certificate'
import { Route as AppTracebackIndexRouteImport } from './routes/app/traceback/index'
import { Route as AppAgreementIndexRouteImport } from './routes/app/agreement/index'
import { Route as AppTracebackTracksRouteImport } from './routes/app/traceback/tracks'
import { Route as AppTracebackSettingsRouteImport } from './routes/app/traceback/settings'
import { Route as AppTracebackNotaryRouteImport } from './routes/app/traceback/notary'
import { Route as AppTracebackConfigRouteImport } from './routes/app/traceback/config'
import { Route as AppTracebackApiRouteImport } from './routes/app/traceback/api'
import { Route as AppAgreementProfileRouteImport } from './routes/app/agreement/profile'
import { Route as AppAgreementLoginRouteImport } from './routes/app/agreement/login'

const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLoginRoute = DemoLoginRouteImport.update({
  id: '/demo-login',
  path: '/demo-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesTestRoute = CertificatesTestRouteImport.update({
  id: '/certificates-test',
  path: '/certificates-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminRoute = PlatformAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PlatformRoute,
} as any)
const AppScriptsRoute = AppScriptsRouteImport.update({
  id: '/app/scripts',
  path: '/app/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/app/pricing',
  path: '/app/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/app/login',
  path: '/app/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/app/help',
  path: '/app/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEditorRoute = AppEditorRouteImport.update({
  id: '/app/editor',
  path: '/app/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChangelogRoute = AppChangelogRouteImport.update({
  id: '/app/changelog',
  path: '/app/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCertificatesDetailRoute = AppCertificatesDetailRouteImport.update({
  id: '/app/certificates-detail',
  path: '/app/certificates-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/app/certificates',
  path: '/app/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCertificateSingleRoute = AppCertificateSingleRouteImport.update({
  id: '/app/certificate-single',
  path: '/app/certificate-single',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCertificateRoute = AppCertificateRouteImport.update({
  id: '/app/certificate',
  path: '/app/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTracebackIndexRoute = AppTracebackIndexRouteImport.update({
  id: '/app/traceback/',
  path: '/app/traceback/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgreementIndexRoute = AppAgreementIndexRouteImport.update({
  id: '/app/agreement/',
  path: '/app/agreement/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTracebackTracksRoute = AppTracebackTracksRouteImport.update({
  id: '/app/traceback/tracks',
  path: '/app/traceback/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTracebackSettingsRoute = AppTracebackSettingsRouteImport.update({
  id: '/app/traceback/settings',
  path: '/app/traceback/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTracebackNotaryRoute = AppTracebackNotaryRouteImport.update({
  id: '/app/traceback/notary',
  path: '/app/traceback/notary',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTracebackConfigRoute = AppTracebackConfigRouteImport.update({
  id: '/app/traceback/config',
  path: '/app/traceback/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTracebackApiRoute = AppTracebackApiRouteImport.update({
  id: '/app/traceback/api',
  path: '/app/traceback/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgreementProfileRoute = AppAgreementProfileRouteImport.update({
  id: '/app/agreement/profile',
  path: '/app/agreement/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgreementLoginRoute = AppAgreementLoginRouteImport.update({
  id: '/app/agreement/login',
  path: '/app/agreement/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/certificates-test': typeof CertificatesTestRoute
  '/demo-login': typeof DemoLoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/app/certificate': typeof AppCertificateRoute
  '/app/certificate-single': typeof AppCertificateSingleRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/certificates-detail': typeof AppCertificatesDetailRoute
  '/app/changelog': typeof AppChangelogRoute
  '/app/editor': typeof AppEditorRoute
  '/app/help': typeof AppHelpRoute
  '/app/login': typeof AppLoginRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/scripts': typeof AppScriptsRoute
  '/platform/admin': typeof PlatformAdminRoute
  '/app/': typeof AppIndexRoute
  '/app/agreement/login': typeof AppAgreementLoginRoute
  '/app/agreement/profile': typeof AppAgreementProfileRoute
  '/app/traceback/api': typeof AppTracebackApiRoute
  '/app/traceback/config': typeof AppTracebackConfigRoute
  '/app/traceback/notary': typeof AppTracebackNotaryRoute
  '/app/traceback/settings': typeof AppTracebackSettingsRoute
  '/app/traceback/tracks': typeof AppTracebackTracksRoute
  '/app/agreement/': typeof AppAgreementIndexRoute
  '/app/traceback/': typeof AppTracebackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/certificates-test': typeof CertificatesTestRoute
  '/demo-login': typeof DemoLoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/app/certificate': typeof AppCertificateRoute
  '/app/certificate-single': typeof AppCertificateSingleRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/certificates-detail': typeof AppCertificatesDetailRoute
  '/app/changelog': typeof AppChangelogRoute
  '/app/editor': typeof AppEditorRoute
  '/app/help': typeof AppHelpRoute
  '/app/login': typeof AppLoginRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/scripts': typeof AppScriptsRoute
  '/platform/admin': typeof PlatformAdminRoute
  '/app': typeof AppIndexRoute
  '/app/agreement/login': typeof AppAgreementLoginRoute
  '/app/agreement/profile': typeof AppAgreementProfileRoute
  '/app/traceback/api': typeof AppTracebackApiRoute
  '/app/traceback/config': typeof AppTracebackConfigRoute
  '/app/traceback/notary': typeof AppTracebackNotaryRoute
  '/app/traceback/settings': typeof AppTracebackSettingsRoute
  '/app/traceback/tracks': typeof AppTracebackTracksRoute
  '/app/agreement': typeof AppAgreementIndexRoute
  '/app/traceback': typeof AppTracebackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/certificates-test': typeof CertificatesTestRoute
  '/demo-login': typeof DemoLoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/app/certificate': typeof AppCertificateRoute
  '/app/certificate-single': typeof AppCertificateSingleRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/certificates-detail': typeof AppCertificatesDetailRoute
  '/app/changelog': typeof AppChangelogRoute
  '/app/editor': typeof AppEditorRoute
  '/app/help': typeof AppHelpRoute
  '/app/login': typeof AppLoginRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/scripts': typeof AppScriptsRoute
  '/platform/admin': typeof PlatformAdminRoute
  '/app/': typeof AppIndexRoute
  '/app/agreement/login': typeof AppAgreementLoginRoute
  '/app/agreement/profile': typeof AppAgreementProfileRoute
  '/app/traceback/api': typeof AppTracebackApiRoute
  '/app/traceback/config': typeof AppTracebackConfigRoute
  '/app/traceback/notary': typeof AppTracebackNotaryRoute
  '/app/traceback/settings': typeof AppTracebackSettingsRoute
  '/app/traceback/tracks': typeof AppTracebackTracksRoute
  '/app/agreement/': typeof AppAgreementIndexRoute
  '/app/traceback/': typeof AppTracebackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/certificates-test'
    | '/demo-login'
    | '/platform'
    | '/app/certificate'
    | '/app/certificate-single'
    | '/app/certificates'
    | '/app/certificates-detail'
    | '/app/changelog'
    | '/app/editor'
    | '/app/help'
    | '/app/login'
    | '/app/pricing'
    | '/app/scripts'
    | '/platform/admin'
    | '/app/'
    | '/app/agreement/login'
    | '/app/agreement/profile'
    | '/app/traceback/api'
    | '/app/traceback/config'
    | '/app/traceback/notary'
    | '/app/traceback/settings'
    | '/app/traceback/tracks'
    | '/app/agreement/'
    | '/app/traceback/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/certificates-test'
    | '/demo-login'
    | '/platform'
    | '/app/certificate'
    | '/app/certificate-single'
    | '/app/certificates'
    | '/app/certificates-detail'
    | '/app/changelog'
    | '/app/editor'
    | '/app/help'
    | '/app/login'
    | '/app/pricing'
    | '/app/scripts'
    | '/platform/admin'
    | '/app'
    | '/app/agreement/login'
    | '/app/agreement/profile'
    | '/app/traceback/api'
    | '/app/traceback/config'
    | '/app/traceback/notary'
    | '/app/traceback/settings'
    | '/app/traceback/tracks'
    | '/app/agreement'
    | '/app/traceback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/certificates-test'
    | '/demo-login'
    | '/platform'
    | '/app/certificate'
    | '/app/certificate-single'
    | '/app/certificates'
    | '/app/certificates-detail'
    | '/app/changelog'
    | '/app/editor'
    | '/app/help'
    | '/app/login'
    | '/app/pricing'
    | '/app/scripts'
    | '/platform/admin'
    | '/app/'
    | '/app/agreement/login'
    | '/app/agreement/profile'
    | '/app/traceback/api'
    | '/app/traceback/config'
    | '/app/traceback/notary'
    | '/app/traceback/settings'
    | '/app/traceback/tracks'
    | '/app/agreement/'
    | '/app/traceback/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CertificatesTestRoute: typeof CertificatesTestRoute
  DemoLoginRoute: typeof DemoLoginRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  AppCertificateRoute: typeof AppCertificateRoute
  AppCertificateSingleRoute: typeof AppCertificateSingleRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppCertificatesDetailRoute: typeof AppCertificatesDetailRoute
  AppChangelogRoute: typeof AppChangelogRoute
  AppEditorRoute: typeof AppEditorRoute
  AppHelpRoute: typeof AppHelpRoute
  AppLoginRoute: typeof AppLoginRoute
  AppPricingRoute: typeof AppPricingRoute
  AppScriptsRoute: typeof AppScriptsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAgreementLoginRoute: typeof AppAgreementLoginRoute
  AppAgreementProfileRoute: typeof AppAgreementProfileRoute
  AppTracebackApiRoute: typeof AppTracebackApiRoute
  AppTracebackConfigRoute: typeof AppTracebackConfigRoute
  AppTracebackNotaryRoute: typeof AppTracebackNotaryRoute
  AppTracebackSettingsRoute: typeof AppTracebackSettingsRoute
  AppTracebackTracksRoute: typeof AppTracebackTracksRoute
  AppAgreementIndexRoute: typeof AppAgreementIndexRoute
  AppTracebackIndexRoute: typeof AppTracebackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-login': {
      id: '/demo-login'
      path: '/demo-login'
      fullPath: '/demo-login'
      preLoaderRoute: typeof DemoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates-test': {
      id: '/certificates-test'
      path: '/certificates-test'
      fullPath: '/certificates-test'
      preLoaderRoute: typeof CertificatesTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/admin': {
      id: '/platform/admin'
      path: '/admin'
      fullPath: '/platform/admin'
      preLoaderRoute: typeof PlatformAdminRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/app/scripts': {
      id: '/app/scripts'
      path: '/app/scripts'
      fullPath: '/app/scripts'
      preLoaderRoute: typeof AppScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pricing': {
      id: '/app/pricing'
      path: '/app/pricing'
      fullPath: '/app/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/login': {
      id: '/app/login'
      path: '/app/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/help': {
      id: '/app/help'
      path: '/app/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/editor': {
      id: '/app/editor'
      path: '/app/editor'
      fullPath: '/app/editor'
      preLoaderRoute: typeof AppEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/changelog': {
      id: '/app/changelog'
      path: '/app/changelog'
      fullPath: '/app/changelog'
      preLoaderRoute: typeof AppChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/certificates-detail': {
      id: '/app/certificates-detail'
      path: '/app/certificates-detail'
      fullPath: '/app/certificates-detail'
      preLoaderRoute: typeof AppCertificatesDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/certificates': {
      id: '/app/certificates'
      path: '/app/certificates'
      fullPath: '/app/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/certificate-single': {
      id: '/app/certificate-single'
      path: '/app/certificate-single'
      fullPath: '/app/certificate-single'
      preLoaderRoute: typeof AppCertificateSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/certificate': {
      id: '/app/certificate'
      path: '/app/certificate'
      fullPath: '/app/certificate'
      preLoaderRoute: typeof AppCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/traceback/': {
      id: '/app/traceback/'
      path: '/app/traceback'
      fullPath: '/app/traceback/'
      preLoaderRoute: typeof AppTracebackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agreement/': {
      id: '/app/agreement/'
      path: '/app/agreement'
      fullPath: '/app/agreement/'
      preLoaderRoute: typeof AppAgreementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/traceback/tracks': {
      id: '/app/traceback/tracks'
      path: '/app/traceback/tracks'
      fullPath: '/app/traceback/tracks'
      preLoaderRoute: typeof AppTracebackTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/traceback/settings': {
      id: '/app/traceback/settings'
      path: '/app/traceback/settings'
      fullPath: '/app/traceback/settings'
      preLoaderRoute: typeof AppTracebackSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/traceback/notary': {
      id: '/app/traceback/notary'
      path: '/app/traceback/notary'
      fullPath: '/app/traceback/notary'
      preLoaderRoute: typeof AppTracebackNotaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/traceback/config': {
      id: '/app/traceback/config'
      path: '/app/traceback/config'
      fullPath: '/app/traceback/config'
      preLoaderRoute: typeof AppTracebackConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/traceback/api': {
      id: '/app/traceback/api'
      path: '/app/traceback/api'
      fullPath: '/app/traceback/api'
      preLoaderRoute: typeof AppTracebackApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agreement/profile': {
      id: '/app/agreement/profile'
      path: '/app/agreement/profile'
      fullPath: '/app/agreement/profile'
      preLoaderRoute: typeof AppAgreementProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agreement/login': {
      id: '/app/agreement/login'
      path: '/app/agreement/login'
      fullPath: '/app/agreement/login'
      preLoaderRoute: typeof AppAgreementLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlatformRouteChildren {
  PlatformAdminRoute: typeof PlatformAdminRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformAdminRoute: PlatformAdminRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CertificatesTestRoute: CertificatesTestRoute,
  DemoLoginRoute: DemoLoginRoute,
  PlatformRoute: PlatformRouteWithChildren,
  AppCertificateRoute: AppCertificateRoute,
  AppCertificateSingleRoute: AppCertificateSingleRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppCertificatesDetailRoute: AppCertificatesDetailRoute,
  AppChangelogRoute: AppChangelogRoute,
  AppEditorRoute: AppEditorRoute,
  AppHelpRoute: AppHelpRoute,
  AppLoginRoute: AppLoginRoute,
  AppPricingRoute: AppPricingRoute,
  AppScriptsRoute: AppScriptsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAgreementLoginRoute: AppAgreementLoginRoute,
  AppAgreementProfileRoute: AppAgreementProfileRoute,
  AppTracebackApiRoute: AppTracebackApiRoute,
  AppTracebackConfigRoute: AppTracebackConfigRoute,
  AppTracebackNotaryRoute: AppTracebackNotaryRoute,
  AppTracebackSettingsRoute: AppTracebackSettingsRoute,
  AppTracebackTracksRoute: AppTracebackTracksRoute,
  AppAgreementIndexRoute: AppAgreementIndexRoute,
  AppTracebackIndexRoute: AppTracebackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
